"""gpu config utilities"""

import os
from pathlib import Path

import torch
import yaml


# gpu config map — base models
_GPU_CONFIG_MAP = {
    # ampere (30-series)
    "3050": "rtx_3050.yaml",
    "3060": "rtx_3060.yaml",
    "3070": "rtx_3070.yaml",
    "3080": "rtx_3080.yaml",
    "3090": "rtx_3090.yaml",

    # ada lovelace (40-series)
    "4060": "rtx_4060.yaml",
    "4070": "rtx_4070.yaml",
    "4080": "rtx_4080.yaml",
    "4090": "rtx_4090.yaml",

    # blackwell (50-series)
    "5060": "rtx_5060.yaml",
    "5070": "rtx_5070.yaml",
    "5080": "rtx_5080.yaml",
    "5090": "rtx_5090.yaml",
}

# variant -> base mapping (checked first, longest match wins)
_GPU_VARIANTS = {
    # 30-series variants
    "3060 Ti": "3070",
    "3070 Ti": "3080",
    "3080 Ti": "3090",
    "3090 Ti": "3090",

    # 40-series variants
    "4060 Ti": "4070",
    "4070 Super": "4070",
    "4070 Ti Super": "4080",
    "4070 Ti": "4070",
    "4080 Super": "4080",

    # 50-series variants
    "5060 Ti": "5070",
    "5070 Ti": "5080",
}


def detect_gpu() -> str | None:
    """detect gpu name"""
    if not torch.cuda.is_available():
        return None
    return torch.cuda.get_device_name(0)


def _find_config_file(gpu_name: str) -> Path | None:
    """find config file"""
    configs_dir = Path(__file__).parent.parent.parent / "configs"
    if not configs_dir.exists():
        configs_dir = Path(__file__).parent.parent / "configs"

    # check variant mappings first (longest match first to avoid partial hits)
    for variant in sorted(_GPU_VARIANTS, key=len, reverse=True):
        if variant in gpu_name:
            base = _GPU_VARIANTS[variant]
            filename = _GPU_CONFIG_MAP.get(base)
            if filename:
                config_path = configs_dir / filename
                if config_path.exists():
                    return config_path

    # check base model
    for key, filename in _GPU_CONFIG_MAP.items():
        if key in gpu_name:
            config_path = configs_dir / filename
            if config_path.exists():
                return config_path
    return None


def load_config(config_path: str | Path) -> dict:
    """load yaml config"""
    with open(config_path, "r") as f:
        return yaml.safe_load(f)


def get_gpu_config() -> dict:
    """load gpu config"""
    gpu_name = detect_gpu()
    if gpu_name is None:
        return {}

    config_path = _find_config_file(gpu_name)
    if config_path is None:
        return {}

    config = load_config(config_path)
    config["_gpu_name"] = gpu_name
    config["_config_file"] = str(config_path)
    return config


def save_autotune_results(results: dict, output_path: str | Path) -> None:
    """save autotune results"""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    gpu_name = detect_gpu() or "unknown"
    data = {
        "gpu": gpu_name,
        "note": "Auto-generated by TinKer autotuning",
        **results,
    }
    with open(output_path, "w") as f:
        yaml.dump(data, f, default_flow_style=False)
